version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:80"

  mapping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

